spring:
  datasource:
    url: jdbc:h2:mem:serverlist
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
server:
  port: 8080